version: '3.7'

services:

  mongo:
    container_name: mongodb
    image: mongo:latest
    restart: always
    
    ports:
      - 27018:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Database2022
